compiler:   ghc-8.0.1
resolver:   nightly-2016-08-11
flags:      {}
extra-deps:
  - http-conduit-2.2.0
  - http-client-0.5.0.1
  - http-client-tls-0.3.0
packages:
  - core
  - test
  - examples
  - amazonka
  - amazonka-conduit

  - amazonka-apigateway
  - amazonka-application-autoscaling
  - amazonka-autoscaling
  - amazonka-certificatemanager
  - amazonka-cloudformation
  - amazonka-cloudfront
  - amazonka-cloudhsm
  - amazonka-cloudsearch
  - amazonka-cloudsearch-domains
  - amazonka-cloudtrail
  - amazonka-cloudwatch
  - amazonka-cloudwatch-events
  - amazonka-cloudwatch-logs
  - amazonka-codecommit
  - amazonka-codedeploy
  - amazonka-codepipeline
  - amazonka-cognito-identity
  - amazonka-cognito-idp
  - amazonka-cognito-sync
  - amazonka-config
  - amazonka-datapipeline
  - amazonka-devicefarm
  - amazonka-directconnect
  - amazonka-discovery
  - amazonka-dms
  - amazonka-ds
  - amazonka-dynamodb
  - amazonka-dynamodb-streams
  - amazonka-ec2
  - amazonka-ecr
  - amazonka-ecs
  - amazonka-efs
  - amazonka-elasticache
  - amazonka-elasticbeanstalk
  - amazonka-elasticsearch
  - amazonka-elastictranscoder
  - amazonka-elb
  - amazonka-elbv2
  - amazonka-emr
  - amazonka-gamelift
  - amazonka-glacier
  - amazonka-iam
  - amazonka-importexport
  - amazonka-inspector
  - amazonka-iot
  - amazonka-iot-dataplane
  - amazonka-kinesis
  - amazonka-kinesis-analytics
  - amazonka-kinesis-firehose
  - amazonka-kms
  - amazonka-lambda
  - amazonka-marketplace-analytics
  - amazonka-marketplace-metering
  - amazonka-ml
  - amazonka-opsworks
  - amazonka-rds
  - amazonka-redshift
  - amazonka-route53
  - amazonka-route53-domains
  - amazonka-s3
  - amazonka-s3-encryption
  - amazonka-sdb
  - amazonka-servicecatalog
  - amazonka-ses
  - amazonka-snowball
  - amazonka-sns
  - amazonka-sqs
  - amazonka-ssm
  - amazonka-storagegateway
  - amazonka-sts
  - amazonka-support
  - amazonka-swf
  - amazonka-waf
  - amazonka-workspaces
